# Generated by Django 5.2.11 on 2026-03-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmedia',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listingmedia',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingmedia',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingmedia',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listingmedia',
            name='storage_key',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
        migrations.AddField(
            model_name='listingmedia',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='listingmedia',
            name='file_url',
            field=models.URLField(blank=True),
        ),
    ]
