# Generated by Django 5.2.11 on 2026-03-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_listingmedia_content_type_listingmedia_file_size_and_more'),
        ('accounts', '0009_feedbacksubmission_rating'),
    ]

    operations = [
    ]
