# Generated by Django 5.2.12 on 2026-03-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_feedbacksubmission_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=16),
        ),
    ]
