# Generated by Django 5.2.12 on 2026-03-29 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_managementcompany_companydocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementcompany',
            name='guidelines',
        ),
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Verve Apartments, The Hub', max_length=200)),
                ('min_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_availability_days', models.PositiveIntegerField(blank=True, null=True)),
                ('utilities_included', models.BooleanField(blank=True, null=True)),
                ('pets_allowed', models.BooleanField(blank=True, null=True)),
                ('furnished_status', models.CharField(blank=True, choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished'), ('partially_furnished', 'Partially Furnished')], max_length=24, null=True)),
                ('required_amenities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='accounts.managementcompany')),
            ],
        ),
    ]
