# Generated by Django 5.2.12 on 2026-03-29 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_managementcompany_guidelines_guideline'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='approved_by_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_listings', to='accounts.managementcompany'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subleaser_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guideline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='accounts.guideline')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='accounts.propertylisting')),
                ('management_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='accounts.managementcompany')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['management_company', 'status', '-created_at'], name='approval_company_status_idx')],
            },
        ),
    ]
