# Generated by Django 5.2.12 on 2026-03-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_propertylisting_approved_by_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='approval_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=16),
        ),
    ]
