# Generated by Django 5.2.13 on 2026-04-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20260329_booking_deposit_and_approval'),
        ('accounts', '0018_user_bio_user_contact_phone_user_profile_picture_url_and_more'),
    ]

    operations = [
    ]
