# Generated by Django 5.2.13 on 2026-04-27 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20260427_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertybooking',
            name='platform_fee_flat_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Company flat fee frozen at booking confirmation time', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertybooking',
            name='platform_fee_percentage_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Company fee percentage frozen at booking confirmation time', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='review',
            field=models.TextField(blank=True, default='', help_text='Optional written review to accompany the numeric rating'),
        ),
        migrations.CreateModel(
            name='CompanyFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Fee as a percentage of monthly rent (e.g. 5.00 = 5%)', max_digits=5, null=True)),
                ('platform_fee_flat', models.DecimalField(blank=True, decimal_places=2, help_text='Flat fee in USD added to each booking', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_config', to='accounts.managementcompany')),
            ],
        ),
    ]
