# Generated by Django 5.2.13 on 2026-04-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_propertybooking_platform_fee_flat_snapshot_and_more'),
        ('accounts', '0024_managementcompany_booking_fee_percent'),
    ]

    operations = [
    ]
