import os
from decimal import Decimal
from pathlib import Path

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-zsa=d&-1tidt2v-(4)&ir6ffb774w_066s%&y%uvh^p)he1jcc"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "storages",
    "accounts",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if os.environ.get("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["POSTGRES_DB"],
            "USER": os.environ["POSTGRES_USER"],
            "PASSWORD": os.environ["POSTGRES_PASSWORD"],
            "HOST": os.environ["POSTGRES_HOST"],
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")
AWS_DEFAULT_REGION = os.environ.get("AWS_DEFAULT_REGION", "")
AWS_S3_PUBLIC_BUCKET_NAME = os.environ.get("AWS_S3_PUBLIC_BUCKET_NAME", "")
AWS_S3_PRIVATE_BUCKET_NAME = os.environ.get("AWS_S3_PRIVATE_BUCKET_NAME", "")
AWS_S3_PUBLIC_CUSTOM_DOMAIN = (
    os.environ.get("AWS_S3_PUBLIC_CUSTOM_DOMAIN", "")
    .strip()
    .removeprefix("https://")
    .removeprefix("http://")
    .strip("/")
)
AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL", "").strip().rstrip("/") or None
AWS_S3_PRIVATE_URL_EXPIRE_SECONDS = int(os.environ.get("AWS_S3_PRIVATE_URL_EXPIRE_SECONDS", "300"))

LISTING_MEDIA_PUBLIC_PREFIX = "listing-media/public"
LISTING_MEDIA_PUBLIC_BASE_URL = ""
LISTING_MEDIA_PRIVATE_PREFIX = "listing-media/private"

if AWS_S3_PUBLIC_BUCKET_NAME:
    public_media_storage_options = {
        "access_key": AWS_ACCESS_KEY_ID or None,
        "secret_key": AWS_SECRET_ACCESS_KEY or None,
        "bucket_name": AWS_S3_PUBLIC_BUCKET_NAME,
        "region_name": AWS_DEFAULT_REGION or None,
        "default_acl": None,
        "querystring_auth": False,
        "file_overwrite": False,
        "location": LISTING_MEDIA_PUBLIC_PREFIX,
    }

    if AWS_S3_ENDPOINT_URL:
        public_media_storage_options["endpoint_url"] = AWS_S3_ENDPOINT_URL

    if AWS_S3_PUBLIC_CUSTOM_DOMAIN:
        public_media_storage_options["custom_domain"] = AWS_S3_PUBLIC_CUSTOM_DOMAIN

    STORAGES["listing_media_public"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": public_media_storage_options,
    }

    if AWS_S3_PUBLIC_CUSTOM_DOMAIN:
        LISTING_MEDIA_PUBLIC_BASE_URL = (
            f"https://{AWS_S3_PUBLIC_CUSTOM_DOMAIN}/{LISTING_MEDIA_PUBLIC_PREFIX}"
        )
    elif AWS_S3_ENDPOINT_URL:
        LISTING_MEDIA_PUBLIC_BASE_URL = (
            f"{AWS_S3_ENDPOINT_URL}/{AWS_S3_PUBLIC_BUCKET_NAME}/{LISTING_MEDIA_PUBLIC_PREFIX}"
        )
    elif AWS_DEFAULT_REGION:
        LISTING_MEDIA_PUBLIC_BASE_URL = (
            f"https://{AWS_S3_PUBLIC_BUCKET_NAME}.s3.{AWS_DEFAULT_REGION}.amazonaws.com/"
            f"{LISTING_MEDIA_PUBLIC_PREFIX}"
        )
    else:
        LISTING_MEDIA_PUBLIC_BASE_URL = (
            f"https://{AWS_S3_PUBLIC_BUCKET_NAME}.s3.amazonaws.com/{LISTING_MEDIA_PUBLIC_PREFIX}"
        )

if AWS_S3_PRIVATE_BUCKET_NAME:
    private_media_storage_options = {
        "access_key": AWS_ACCESS_KEY_ID or None,
        "secret_key": AWS_SECRET_ACCESS_KEY or None,
        "bucket_name": AWS_S3_PRIVATE_BUCKET_NAME,
        "region_name": AWS_DEFAULT_REGION or None,
        "default_acl": None,
        "querystring_auth": True,
        "querystring_expire": AWS_S3_PRIVATE_URL_EXPIRE_SECONDS,
        "file_overwrite": False,
        "location": LISTING_MEDIA_PRIVATE_PREFIX,
    }

    if AWS_S3_ENDPOINT_URL:
        private_media_storage_options["endpoint_url"] = AWS_S3_ENDPOINT_URL

    STORAGES["listing_media_private"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": private_media_storage_options,
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_ALL_ORIGINS = True  # dev only
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173", "http://127.0.0.1:5173"]
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
}

REDIS_URL = os.environ.get("REDIS_URL")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

# Email (verification links, 2FA codes).
# Default: console backend prints to terminal (no real delivery). To send real email, set:
#   EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#   EMAIL_HOST=smtp.example.com  EMAIL_PORT=587  EMAIL_USE_TLS=True
#   EMAIL_HOST_USER=...  EMAIL_HOST_PASSWORD=...
# (e.g. Gmail, SendGrid, Mailgun).
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@boilerlease.local")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
# Frontend base URL for verification links (e.g. http://localhost:5173)
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")

# Flat platform fee shown in booking price breakdown.
PLATFORM_BOOKING_FEE_FLAT = Decimal(os.environ.get("PLATFORM_BOOKING_FEE_FLAT", "3.99"))
# Backend base URL for links in emails (e.g. http://localhost:8000)
BACKEND_URL = os.environ.get("BACKEND_URL", "http://localhost:8000").rstrip("/")

# Stripe
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
