from django.urls import path

from . import views

urlpatterns = [
    path("auth/csrf/", views.csrf_cookie),
    path("auth/register/", views.register),
    path("auth/login/", views.login_view),
    path("auth/logout/", views.logout_view),
    path("auth/password-reset/request/", views.password_reset_request),
    path("auth/password-reset/confirm/", views.password_reset_confirm),
    path("auth/me/", views.current_user),
    path("account/", views.current_user),
    path("account/password/", views.change_password),
    path("auth/2fa/", views.verify_2fa_login),
    path("auth/send-verification-email/", views.send_verification_email_view),
    path("auth/verify-email/", views.verify_email_view),
    path("account/settings/", views.account_settings),
    path("account/2fa/enable/", views.two_factor_enable),
    path("account/2fa/disable/", views.two_factor_disable),
    path("help/feedback/", views.submit_help_feedback),
    path("listings/browse/", views.browse_property_listings),
    path("listings/", views.create_property_listing),
    path("listings/<int:listing_id>/media/", views.upload_listing_media),
    path("listings/<int:listing_id>/media/<int:media_id>/primary/", views.set_listing_media_primary),
    path("listings/<int:listing_id>/", views.property_listing_detail),
    path("listings/mine/", views.my_property_listings),
    path("listings/amenities/", views.listing_amenities),
    path("listings/media/reorder/", views.reorder_listing_media),
    path("listings/media/<int:media_id>/", views.delete_listing_media),
    path("listings/media/<int:media_id>/private-access/", views.private_media_access),
    path("bookings/", views.create_booking),
    path("bookings/<int:booking_id>/", views.cancel_booking),
    path("bookings/history/", views.my_booking_history),
    path("bookings/current/", views.my_current_bookings),
    path("bookings/past/", views.my_past_bookings),
    path("payments/history/", views.my_payment_history),
    path("payments/checkout/deposit/", views.create_deposit_checkout_session),
    path("payments/webhook/", views.stripe_webhook),
    path("favorites/", views.my_favorite_listings),
    path("favorites/<int:listing_id>/", views.favorite_listing_toggle),
    path("company/status/", views.company_status),
    path("company/documents/", views.company_documents),
    path("company/documents/<int:pk>/", views.company_document_delete),
    path("company/guidelines/", views.company_guidelines),
    path("company/guidelines/<int:pk>/", views.company_guideline_detail),
    path("companies/", views.browse_management_companies),
]
